services:
  app:
    container_name: music-app
    image: music-app-iamge:latest
    build:
      context: .
      dockerfile: Dockerfile.app
      tags:
      - "music-app-image:latest"
    env_file: '.env'
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - './${LOGS_DIR}:/go/logs/'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${POSTGRES_HOST}
    image: music-postgres-image:latest
    build:
      context: .
      dockerfile: Dockerfile.postgres
      tags:
      - "music-postgres-image:latest"
    expose:
      - "${POSTGRES_PORT}"
    env_file: '.env'
    volumes:
      - 'postgres_data:/var/lib/postgersql/data'
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
    driver: local