services:
  app:
    container_name: music-app-container
    image: music-app-image
    build:
      context: .
      dockerfile: Dockerfile.app
      tags:
      - "music-app-image:latest"
    env_file: 'default.env'
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - '${OUTTER_LOGS_DIR}:/go/logs/'

  postgres:
    container_name: music-postgres-container
    image: music-postgres-image:latest
    build:
      context: .
      dockerfile: Dockerfile.postgres
      tags:
      - "music-postgres-image:latest"
    expose:
      - "${POSTGRES_PORT}"
    env_file: 'default.env'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'postgres_data:/var/lib/postgersql/data'

volumes:
  postgres_data:
    driver: local